postprocessor:
  name: rff
  APS_mode: True
  postprocessor_args:
    sigma: 0.5
    D: 1024
    alpha: 0.05
    feature_space: penultimate
    normalize: True
    diagnose: True
    debug: False
    score_mode: max
    variance_weighted: True
  postprocessor_sweep:
    sigma: [0.1, 0.5, 1.0, 2.0]
    D: [512, 1024, 2048]
    alpha: [0.025, 0.05, 0.10]
